import { createApp } from "vue";
import { createRouter } from "vue-router";
import { App } from "./App";
import { routes } from "./config/router";
import { createWebHashHistory } from "vue-router";
const history = createWebHashHistory();
const router = createRouter({ history, routes });
const app = createApp(App);
app.use(router);
app.mount("#app");
